apiVersion: v1
kind: Namespace
metadata:
  name: cs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zipcode
  name: zipcode
  namespace: cs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipcode
  template:
    metadata:
      labels:
        app: zipcode
    spec:
      containers:
      - image: registry.localhost:5000/api-zipcode:1.0.0
        name: zipcode
        ports:
        - containerPort: 1401
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: zipcode
  namespace: cs
spec:
  ports:
  - port: 1401
    protocol: TCP
    targetPort: 1401
  selector:
    app: zipcode
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: zipcode-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.frontend.rule.type: PathPrefixStrip
  namespace: cs
spec:
  rules:
  - http:
      paths:
      - path: /cs
        backend:
          serviceName: zipcode
          servicePort: 1401          